name = "Modinga"
author = "Sephiroth1993"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0956eaedd95fa189c83b36e49fd9646f76f0fc7de0f1622db3f56bb0de570c2"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
