name = "Modinga"
author = "Sephiroth1993"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a561e4fd370d2d6db20bf0860da00a56d1ea4b36159d095a46c543d151a1cc3"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
