name = "Modinga"
author = "Sephiroth1993"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcd64ec14bfd31b00f58dd4c612fef269f16f8da6dd83d406db7955de633735e"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
