name = "Modinga"
author = "Sephiroth1993"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb3157a914c0cceee7510b05bf728af73d8f068556ddc852c79676c3013f017d"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
