name = "Modinga"
author = "Sephiroth1993"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a49cd63baf236da6d038113707b35b7ed98e515a26eb575aca5ec1d387d220f"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
